name: app2
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.2
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.10
  qr_flutter: ^3.1.0
  material_design_icons_flutter: ^4.0.5755
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - Assets/Fonts/Cormorant_Garamond/

  fonts:
  - family: Cormorant_Garamond
    fonts:
    - asset: Assets/Fonts/Cormorant_Garamond/CormorantGaramond-Regular.ttf
#      weight: 900